#!/usr/bin/env sh
dir=`dirname "$(readlink -f "$0")"`
count=5
tail -n$count $dir/log \
  | cut -d ' ' -f 2 \
  | python3 -c 'import sys; from statistics import mean; \
    print(f"{mean(float(l) for l in sys.stdin):.2f}")'
